import type { TemplateDefinition } from "./types";

export const defaultTemplateMusicUrl = "/assets/audio/badr-sara-wedding-3.mp3";

export const featuredOneTemplate: TemplateDefinition = {
  id: "tpl_featured_one",
  slug: "featured-1",
  name: "Featured 1",
  arabicName: "مميز 1",
  category: "كوكتيل مميز",
  style: "featured",
  concept: "قالب مميز يجمع واجهة سينمائية فاخرة، جدول تفاصيل هادئ، صور رومانسية، ومصور ناعم في تجربة واحدة.",
  opening: "Cinematic photo story",
  layout: "Hero بصورة كاملة وأسماء سينمائية، جدول اليوم والقاعة، عداد أفقي، صور رومانسية، خريطة، مصور، RSVP وQR.",
  typography: "أسماء كبيرة بتباين سينمائي مع تفاصيل عربية واضحة ومريحة للقراءة على الهاتف.",
  palette: {
    primary: "#0a1110",
    secondary: "#fdfbf7",
    accent: "#d4af37",
    ink: "#f7efe1",
    surface: "#fffaf4",
  },
  previewImage: "/assets/templates/featured-1.svg",
  accentImage: "/assets/invite/badr-sarah-1.jpeg",
  musicUrl: defaultTemplateMusicUrl,
  enabled: true,
  score: 100,
};

export const cinematicRoseTemplate: TemplateDefinition = {
  id: "tpl_cinematic_rose",
  slug: "cinematic-rose",
  name: "Cinematic Rose",
  arabicName: "سينمائي وردي",
  category: "قالب سينمائي رومانسي",
  style: "cinematic",
  concept: "غلاف سينمائي كامل الشاشة، بطاقة زجاجية عائمة للتاريخ والعداد، ومعرض صور داكن بلمسة وردية.",
  opening: "Full-screen cinematic cover",
  layout: "Hero بصورة كاملة، بطاقة موعد وعداد، رسالة رومانسية، صور متبادلة، خريطة، مصور، RSVP وQR.",
  typography: "أسماء كبيرة فوق صورة داكنة مع تفاصيل وردية ناعمة ومساحات مريحة للهاتف.",
  palette: {
    primary: "#0a0a0a",
    secondary: "#171317",
    accent: "#f0a8ba",
    ink: "#f7edf1",
    surface: "#121012",
  },
  previewImage: "/assets/templates/cinematic-rose.svg",
  accentImage: "/assets/invite/badr-sarah-1.jpeg",
  musicUrl: defaultTemplateMusicUrl,
  enabled: true,
  score: 96,
};

export const modernCinematicTemplate: TemplateDefinition = {
  id: "tpl_modern_cinematic",
  slug: "modern-cinematic",
  name: "Modern Cinematic",
  arabicName: "سينمائي حديث",
  category: "قالب فيلم حديث",
  style: "cinematic",
  concept: "تجربة تشبه ملصق فيلم وثائقي، صورة غلاف قوية، شريط معلومات، معرض أفقي، ولمسات ذهبية هادئة.",
  opening: "Film poster hero",
  layout: "Hero فيلمي، شريط تاريخ ووقت، عداد، معرض صور بالسحب، خريطة داكنة، مصور، RSVP وQR.",
  typography: "عناوين Serif كبيرة مع ألوان ذهبية سينمائية وتفاصيل مختصرة تناسب الموبايل.",
  palette: {
    primary: "#0a0a0a",
    secondary: "#141414",
    accent: "#c0a080",
    ink: "#eaeaea",
    surface: "#101010",
  },
  previewImage: "/assets/templates/modern-cinematic.svg",
  accentImage: "/assets/invite/badr-sarah-2.jpeg",
  musicUrl: defaultTemplateMusicUrl,
  enabled: true,
  score: 95,
};

export const etherealGlassTemplate: TemplateDefinition = {
  id: "tpl_ethereal_glass",
  slug: "ethereal-glass",
  name: "Ethereal Glass",
  arabicName: "زجاجي حالم",
  category: "قالب زجاجي رومانسي",
  style: "glass",
  concept: "خلفية صورة ثابتة مع بطاقات زجاجية شفافة، معرض صور متداخل، وتفاصيل ناعمة كأنها عائمة فوق الصورة.",
  opening: "Fixed glass photo story",
  layout: "خلفية ثابتة، أسماء كبيرة، بطاقة تفاصيل زجاجية، معرض متداخل، خريطة، مصور، RSVP وQR.",
  typography: "أسماء رومانسية كبيرة مع نصوص بيضاء شفافة وتباين زجاجي واضح على الهاتف.",
  palette: {
    primary: "#111111",
    secondary: "#ffffff",
    accent: "#ffffff",
    ink: "#ffffff",
    surface: "#ffffff",
  },
  previewImage: "/assets/templates/ethereal-glass.svg",
  accentImage: "/assets/invite/badr-sarah-3.jpeg",
  musicUrl: defaultTemplateMusicUrl,
  enabled: true,
  score: 94,
};

export const botanicalThemeTemplate: TemplateDefinition = {
  id: "tpl_botanical_theme",
  slug: "botanical-theme",
  name: "Botanical Theme",
  arabicName: "نباتي هادئ",
  category: "قالب نباتي هادئ",
  style: "garden",
  concept: "دعوة خضراء ناعمة بكارت أسماء مقوس، عداد داكن، صورة كبيرة، خريطة واضحة، ولمسة تصوير طبيعية.",
  opening: "Soft botanical card",
  layout: "كارت أسماء نباتي، عداد، صورة غلاف، خريطة، مصور، RSVP وQR.",
  typography: "أسماء كبيرة رقيقة مع ألوان خضراء مطفية وتفاصيل عربية بسيطة ومريحة على الهاتف.",
  palette: {
    primary: "#f0f4f0",
    secondary: "#e2e8e2",
    accent: "#8fbc8f",
    ink: "#2c4c3b",
    surface: "#ffffff",
  },
  previewImage: "/assets/templates/botanical-theme.svg",
  accentImage: "/assets/invite/badr-sarah-1.jpeg",
  musicUrl: defaultTemplateMusicUrl,
  enabled: true,
  score: 93,
};

export const royalGoldTemplate: TemplateDefinition = {
  id: "tpl_royal_gold",
  slug: "royal-gold",
  name: "Royal Gold",
  arabicName: "ملكي ذهبي",
  category: "قالب ملكي أسود ذهبي",
  style: "royal",
  concept: "دعوة ملكية داكنة بإطارات ذهبية، أسماء كبيرة، صورة غلاف فاخرة، خريطة كلاسيكية، وQR أنيق.",
  opening: "Royal black gold",
  layout: "أسماء ملكية، شريط تاريخ ووقت، صورة غلاف، عداد، خريطة، RSVP وQR.",
  typography: "أسماء Serif كبيرة مع ذهب هادئ فوق خلفية سوداء فاخرة وتباين واضح للهاتف.",
  palette: {
    primary: "#0a0a0a",
    secondary: "#16120a",
    accent: "#d4af37",
    ink: "#ffffff",
    surface: "#111111",
  },
  previewImage: "/assets/templates/royal-gold.svg",
  accentImage: "/assets/invite/badr-sarah-1.jpeg",
  musicUrl: defaultTemplateMusicUrl,
  enabled: true,
  score: 94,
};

export const bohoSandTemplate: TemplateDefinition = {
  id: "tpl_boho_sand",
  slug: "boho-sand",
  name: "Boho Sand",
  arabicName: "بوهو رملي",
  category: "قالب بوهو دافئ",
  style: "boho",
  concept: "دعوة بوهو هادئة بألوان رملية، صورة مقوسة، أسماء بسيطة، شريط موعد ناعم، وخريطة مريحة.",
  opening: "Warm boho portrait",
  layout: "صورة مقوسة، أسماء واضحة، موعد داخل كبسولة، عداد، خريطة، RSVP وQR.",
  typography: "خطوط كبيرة ناعمة مع ألوان دافئة ومساحات بسيطة تناسب الهاتف.",
  palette: {
    primary: "#faf3e0",
    secondary: "#e8c39e",
    accent: "#8b4513",
    ink: "#8b4513",
    surface: "#ffffff",
  },
  previewImage: "/assets/templates/boho-sand.svg",
  accentImage: "/assets/invite/badr-sarah-1.jpeg",
  musicUrl: defaultTemplateMusicUrl,
  enabled: true,
  score: 92,
};

export const pureWhiteTemplate: TemplateDefinition = {
  id: "tpl_pure_white",
  slug: "pure-white",
  name: "Pure White",
  arabicName: "أبيض نقي",
  category: "قالب مينيمال أبيض",
  style: "minimal",
  concept: "دعوة بيضاء شديدة البساطة، أسماء كبيرة، صورة Grayscale، موعد نظيف، وخريطة وQR بدون زحمة.",
  opening: "Minimal white editorial",
  layout: "أسماء كبيرة، صورة أبيض وأسود، موعد، عداد، خريطة، RSVP وQR.",
  typography: "خطوط خفيفة ومساحات بيضاء واسعة لتجربة راقية وهادئة على الهاتف.",
  palette: {
    primary: "#ffffff",
    secondary: "#f5f5f5",
    accent: "#111111",
    ink: "#111111",
    surface: "#ffffff",
  },
  previewImage: "/assets/templates/pure-white.svg",
  accentImage: "/assets/invite/badr-sarah-1.jpeg",
  musicUrl: defaultTemplateMusicUrl,
  enabled: true,
  score: 91,
};

export const royalEnvelopeTemplate: TemplateDefinition = {
  id: "tpl_royal_envelope",
  slug: "royal-envelope",
  name: "Royal Envelope",
  arabicName: "كلاسيك ملكي",
  category: "قالب ملكي فاتح",
  style: "royal",
  concept: "ظرف ملكي يفتح بهدوء وتظهر منه بطاقة الدعوة بتفاصيل ذهبية ناعمة.",
  opening: "Envelope reveal",
  layout: "Hero بظرف تفاعلي، تفاصيل الفرح، العد التنازلي، الخريطة، وتأكيد الحضور.",
  typography: "خط عربي واضح مع أرقام إنجليزية وتباين مريح للموبايل.",
  palette: {
    primary: "#f8f4ec",
    secondary: "#d8c19a",
    accent: "#b48b39",
    ink: "#3a2e1f",
    surface: "#ffffff",
  },
  previewImage: "/assets/templates/royal-envelope.svg",
  accentImage: "/assets/brand/champagne-rings.png",
  musicUrl: defaultTemplateMusicUrl,
  enabled: true,
  score: 100,
};

export const luxeNoirTemplate: TemplateDefinition = {
  id: "tpl_luxe_noir",
  slug: "luxe-noir",
  name: "Luxe Noir",
  arabicName: "فخم داكن",
  category: "قالب فاخر داكن",
  style: "noir",
  concept: "دعوة سوداء ذهبية فخمة، صور كبيرة، كروت زجاجية، وخريطة واضحة بتأثير راقٍ.",
  opening: "Envelope reveal",
  layout: "واجهة داكنة، بطاقة أسماء ذهبية، رسالة مختصرة، معرض صور، خريطة، مصور، RSVP وQR.",
  typography: "حروف كبيرة ومريحة للموبايل مع تباين ذهبي واضح وأرقام إنجليزية.",
  palette: {
    primary: "#0d0b09",
    secondary: "#1b1713",
    accent: "#d7a84d",
    ink: "#fff6df",
    surface: "#15120f",
  },
  previewImage: "/assets/templates/luxe-noir.svg",
  accentImage: "/assets/invite/badr-sarah-2.jpeg",
  musicUrl: defaultTemplateMusicUrl,
  enabled: true,
  score: 96,
};

export const ivoryArchesTemplate: TemplateDefinition = {
  id: "tpl_ivory_arches",
  slug: "ivory-arches",
  name: "Ivory Arches",
  arabicName: "رومانسي ناعم",
  category: "قالب رومانسي كريمي",
  style: "ivory",
  concept: "دعوة عاجية هادئة، أسماء كبيرة، صور بأقواس رومانسية، وتفاصيل ناعمة جدًا للموبايل.",
  opening: "Envelope reveal",
  layout: "غلاف Save The Date، عداد داخل بطاقة بيضاء، معرض صور بأقواس، خريطة، مصور، RSVP وQR.",
  typography: "خطوط ناعمة وواضحة مع ألوان حجرية ووردي خفيف للمظهر الراقي.",
  palette: {
    primary: "#fdfbf7",
    secondary: "#eee8df",
    accent: "#d88b9a",
    ink: "#2f2a25",
    surface: "#ffffff",
  },
  previewImage: "/assets/templates/ivory-arches.svg",
  accentImage: "/assets/invite/badr-sarah-1.jpeg",
  musicUrl: defaultTemplateMusicUrl,
  enabled: true,
  score: 94,
};

export const mobileGoldTemplate: TemplateDefinition = {
  id: "tpl_mobile_gold",
  slug: "mobile-gold",
  name: "Mobile Gold",
  arabicName: "ذهبي عصري",
  category: "باقة موبايل ذهبية",
  style: "mobile",
  concept: "دعوة مصممة كأنها شاشة هاتف أنيقة: أسماء واضحة، كروت خفيفة، صور Collage، وخريطة وأزرار لمس كبيرة.",
  opening: "Envelope reveal",
  layout: "تجربة بعرض هاتف، غلاف بسيط، كروت التاريخ والوقت، صور، رسالة، خريطة، مصور، RSVP وQR.",
  typography: "خطوط واضحة جدًا ومساحات صغيرة مناسبة للقراءة السريعة على الهاتف.",
  palette: {
    primary: "#fafafa",
    secondary: "#ffffff",
    accent: "#d4af37",
    ink: "#1a1a1a",
    surface: "#ffffff",
  },
  previewImage: "/assets/templates/mobile-gold.svg",
  accentImage: "/assets/invite/badr-sarah-3.jpeg",
  musicUrl: defaultTemplateMusicUrl,
  enabled: true,
  score: 92,
};

export const softGoldTemplate: TemplateDefinition = {
  id: "tpl_soft_gold",
  slug: "soft-gold",
  name: "Soft Gold",
  arabicName: "ذهبي بسيط",
  category: "قالب ذهبي ناعم",
  style: "mobile",
  concept: "دعوة بيضاء ذهبية خفيفة بعرض موبايل، أسماء واضحة، كروت تاريخ، صور Collage، وخريطة ومشاركة سريعة.",
  opening: "Envelope reveal",
  layout: "غلاف بسيط، كروت التاريخ والوقت، عد تنازلي، معرض صور، رسالة، خريطة، مصور، RSVP وQR.",
  typography: "خطوط واضحة ومساحات مريحة تشبه الكود المرفق بدون تغيير في هيئة التجربة.",
  palette: {
    primary: "#fafafa",
    secondary: "#ffffff",
    accent: "#d4af37",
    ink: "#2a2a2a",
    surface: "#ffffff",
  },
  previewImage: "/assets/templates/soft-gold.svg",
  accentImage: "/assets/invite/badr-sarah-2.jpeg",
  musicUrl: defaultTemplateMusicUrl,
  enabled: true,
  score: 90,
};

export const bohoChicTemplate: TemplateDefinition = {
  id: "tpl_boho_chic",
  slug: "boho-chic",
  name: "Boho Chic",
  arabicName: "بوهو ترندي",
  category: "قالب Boho Sage",
  style: "boho",
  concept: "دعوة ترابية ناعمة بصورة غلاف كبيرة، كروت بيضاء، معرض أفقي، وخريطة خضراء هادئة.",
  opening: "Cinematic photo cover",
  layout: "غلاف بصورة كاملة، بطاقة تاريخ وعد تنازلي، معرض صور أفقي، خريطة، مصور، RSVP وQR.",
  typography: "خطوط كلاسيكية ناعمة مع ألوان Sage وSand ومظهر هادئ مناسب للموبايل.",
  palette: {
    primary: "#f7f5f0",
    secondary: "#e2d8c8",
    accent: "#9cafa4",
    ink: "#3e453c",
    surface: "#ffffff",
  },
  previewImage: "/assets/templates/boho-chic.svg",
  accentImage: "/assets/invite/badr-sarah-1.jpeg",
  musicUrl: defaultTemplateMusicUrl,
  enabled: true,
  score: 91,
};

export const gardenEleganceTemplate: TemplateDefinition = {
  id: "tpl_garden_elegance",
  slug: "garden-elegance",
  name: "Garden Elegance",
  arabicName: "حدائق أنيقة",
  category: "قالب حديقة أنيق",
  style: "garden",
  concept: "دعوة طبيعية هادئة بدوائر أسماء متداخلة، صورة مقوسة، تفاصيل Timeline، وخريطة وQR بتصميم تذكرة.",
  opening: "Organic reveal",
  layout: "غلاف طبيعي، صورة مقوسة، تفاصيل الزمان والمكان، عداد، خريطة، معرض صور، مصور، RSVP وQR.",
  typography: "خطوط رقيقة وواضحة مع أخضر Sage ولمسة وردية ترابية تناسب الهاتف.",
  palette: {
    primary: "#f4f6f0",
    secondary: "#e2e6d8",
    accent: "#ca7d60",
    ink: "#2c3b2e",
    surface: "#ffffff",
  },
  previewImage: "/assets/templates/garden-elegance.svg",
  accentImage: "/assets/invite/badr-sarah-1.jpeg",
  musicUrl: defaultTemplateMusicUrl,
  enabled: true,
  score: 93,
};

export const cinematicStoryTemplate: TemplateDefinition = {
  id: "tpl_cinematic_story",
  slug: "cinematic-story",
  name: "Cinematic Story",
  arabicName: "سينمائي فاخر",
  category: "قالب سينمائي داكن",
  style: "cinematic",
  concept: "دعوة سينمائية بخلفية زمرد داكن، صورة كاملة، أسماء كبيرة، كارت زجاجي، صور متراكبة وQR فاخر.",
  opening: "Cinematic photo story",
  layout: "Hero بصورة كاملة، بطاقة موعد وعد تنازلي، معرض صور متراكب، خريطة، مصور، RSVP وQR.",
  typography: "خطوط كبيرة وفاخرة بتباين أبيض وذهبي فوق خلفية زمردية داكنة مناسبة للموبايل.",
  palette: {
    primary: "#0a1110",
    secondary: "#131f1c",
    accent: "#d4af37",
    ink: "#e8efe5",
    surface: "#1a2e29",
  },
  previewImage: "/assets/templates/cinematic-story.svg",
  accentImage: "/assets/invite/badr-sarah-1.jpeg",
  musicUrl: defaultTemplateMusicUrl,
  enabled: true,
  score: 95,
};

export const invitationTemplates: TemplateDefinition[] = [
  featuredOneTemplate,
  cinematicRoseTemplate,
  modernCinematicTemplate,
  etherealGlassTemplate,
  botanicalThemeTemplate,
  royalGoldTemplate,
  bohoSandTemplate,
  pureWhiteTemplate,
  royalEnvelopeTemplate,
  luxeNoirTemplate,
  ivoryArchesTemplate,
  mobileGoldTemplate,
  bohoChicTemplate,
  softGoldTemplate,
  gardenEleganceTemplate,
  cinematicStoryTemplate,
];

export function getTemplateBySlug(slug: string) {
  return invitationTemplates.find((template) => template.slug === slug);
}

export function getTemplateSortOrder(slug: string) {
  const index = invitationTemplates.findIndex((template) => template.slug === slug);
  return index >= 0 ? index + 1 : invitationTemplates.length + 1;
}

export const featuredTemplates = invitationTemplates;
