import type { TemplateDefinition } from "./types";

export const invitationTemplates: TemplateDefinition[] = [
  {
    id: "tpl_01",
    slug: "royal-envelope",
    name: "Royal Envelope",
    arabicName: "ظرف ملكي",
    category: "فاخر ملكي",
    style: "royal",
    concept: "ظرف شامبانيا يفتح بهدوء وتخرج منه بطاقة الدعوة الذهبية.",
    opening: "Envelope reveal",
    layout: "بطاقة مركزية بطبقات ورقية وختم ذهبي.",
    typography: "خط عربي كلاسيكي بعناوين كبيرة وتفاصيل دقيقة.",
    palette: { primary: "#efe3ca", secondary: "#9d7a36", accent: "#f8d887", ink: "#2f2418", surface: "#fff9ee" },
    previewImage: "/assets/templates/royal-envelope.png",
    accentImage: "/assets/brand/champagne-rings.png",
    enabled: true,
    score: 98,
  },
  {
    id: "tpl_02",
    slug: "modern-cinema",
    name: "Modern Cinema",
    arabicName: "سينما مودرن",
    category: "سينمائي معاصر",
    style: "cinematic",
    concept: "تجربة شاشة كاملة بإحساس فيلم افتتاحي وتايبوجرافي كبير.",
    opening: "Cinematic fade",
    layout: "Hero كامل، شريط تفاصيل، ومقاطع تتحرك مع التمرير.",
    typography: "Sans عربي حديث مع تباين قوي.",
    palette: { primary: "#111111", secondary: "#f5f2ea", accent: "#d4af37", ink: "#f8f5ef", surface: "#171717" },
    previewImage: "/assets/templates/modern-cinema.png",
    accentImage: "/assets/brand/cinema-frame.png",
    enabled: true,
    score: 97,
  },
  {
    id: "tpl_03",
    slug: "arabic-heritage",
    name: "Arabic Heritage",
    arabicName: "تراث عربي",
    category: "تراثي راقي",
    style: "heritage",
    concept: "زخارف عربية دقيقة مع مدخل يشبه فتح باب قصر قديم.",
    opening: "Mosaic door",
    layout: "قوس عربي، شريط زخرفة، وتقسيمات هندسية.",
    typography: "عناوين بنكهة خطية وتفاصيل مقروءة.",
    palette: { primary: "#f6ead8", secondary: "#0f5c55", accent: "#c98b3b", ink: "#25312f", surface: "#fffaf2" },
    previewImage: "/assets/templates/arabic-heritage.png",
    accentImage: "/assets/brand/mosaic.png",
    enabled: true,
    score: 96,
  },
  {
    id: "tpl_04",
    slug: "white-palace",
    name: "White Palace",
    arabicName: "القصر الأبيض",
    category: "قصر أوروبي",
    style: "palace",
    concept: "أعمدة بيضاء، ضوء صباحي، وشعور حفلات القصور.",
    opening: "Curtain lift",
    layout: "محاور متناظرة ومساحات بيضاء واسعة.",
    typography: "Serif ناعم مع أرقام واضحة.",
    palette: { primary: "#f8f6f0", secondary: "#bec7bd", accent: "#b88a44", ink: "#2a2d2a", surface: "#ffffff" },
    previewImage: "/assets/templates/white-palace.png",
    accentImage: "/assets/brand/palace-column.png",
    enabled: true,
    score: 95,
  },
  {
    id: "tpl_05",
    slug: "golden-night",
    name: "Golden Night",
    arabicName: "ليلة ذهبية",
    category: "ليلي فاخر",
    style: "night",
    concept: "سماء داكنة ولمعات ذهبية كأن الدعوة تظهر وسط حفلة ليلية.",
    opening: "Golden spark",
    layout: "عنوان عريض، بطاقة تفاصيل مضيئة، وعداد بارز.",
    typography: "خط حديث بوزن ثقيل للعناوين.",
    palette: { primary: "#14100d", secondary: "#5a3322", accent: "#f1bd57", ink: "#fff6e4", surface: "#211812" },
    previewImage: "/assets/templates/golden-night.png",
    accentImage: "/assets/brand/gold-spark.png",
    enabled: true,
    score: 95,
  },
  {
    id: "tpl_06",
    slug: "floral-garden",
    name: "Floral Garden",
    arabicName: "حديقة زهور",
    category: "رومانسي ناعم",
    style: "floral",
    concept: "زهور مائية تتحرك حول أسماء العروسين.",
    opening: "Petal drift",
    layout: "إطار وردي، بطاقات شفافة، وسجل حضور رقيق.",
    typography: "خط ناعم ومسافات مريحة.",
    palette: { primary: "#fff1f3", secondary: "#7d9d7a", accent: "#d9768f", ink: "#40262e", surface: "#fffafd" },
    previewImage: "/assets/templates/floral-garden.png",
    accentImage: "/assets/brand/petals.png",
    enabled: true,
    score: 94,
  },
  {
    id: "tpl_07",
    slug: "moonlight",
    name: "Moonlight",
    arabicName: "ضوء القمر",
    category: "هادئ شاعري",
    style: "celestial",
    concept: "قمر مضيء، طبقات ضبابية، وانتقال هادئ للأقسام.",
    opening: "Moon rise",
    layout: "مسارات دائرية وعداد في مدار بصري.",
    typography: "عناوين رفيعة وسطور قصيرة.",
    palette: { primary: "#e9edf2", secondary: "#3f5f6f", accent: "#c9d6df", ink: "#17242b", surface: "#f9fbff" },
    previewImage: "/assets/templates/moonlight.png",
    accentImage: "/assets/brand/moon.png",
    enabled: true,
    score: 94,
  },
  {
    id: "tpl_08",
    slug: "black-tie",
    name: "Black Tie",
    arabicName: "بلاك تاي",
    category: "رسمي فاخر",
    style: "editorial",
    concept: "دعوة سوداء رسمية بإحساس حفلات gala.",
    opening: "Velvet split",
    layout: "تباين حاد، تفاصيل قليلة، وتركيز كامل على الأسماء.",
    typography: "Editorial serif مع أرقام كبيرة.",
    palette: { primary: "#080808", secondary: "#f4efe6", accent: "#c7a76c", ink: "#fdfaf5", surface: "#111111" },
    previewImage: "/assets/templates/black-tie.png",
    accentImage: "/assets/brand/velvet.png",
    enabled: true,
    score: 93,
  },
  {
    id: "tpl_09",
    slug: "bohemian-romance",
    name: "Bohemian Romance",
    arabicName: "رومانسية بوهيمية",
    category: "طبيعي دافئ",
    style: "bohemian",
    concept: "أقمشة طبيعية، أعشاب pampas، وتكوين حر.",
    opening: "Fabric sway",
    layout: "شبكة غير متناظرة وصور بحواف عضوية.",
    typography: "خط دافئ وسهل القراءة.",
    palette: { primary: "#f5e4d0", secondary: "#9b7255", accent: "#c18766", ink: "#3c2d25", surface: "#fff7ef" },
    previewImage: "/assets/templates/bohemian-romance.png",
    accentImage: "/assets/brand/pampas.png",
    enabled: true,
    score: 92,
  },
  {
    id: "tpl_10",
    slug: "vintage-love",
    name: "Vintage Love",
    arabicName: "حب كلاسيكي",
    category: "فينتج",
    style: "classic",
    concept: "ورق قديم، طابع بريد، ومشهد دعوة كرسالة حب.",
    opening: "Postcard flip",
    layout: "بطاقة بريدية، تفاصيل مطبوعة، وختم تاريخ.",
    typography: "خط كلاسيكي دافئ.",
    palette: { primary: "#eee0c7", secondary: "#8d4d3d", accent: "#b8845a", ink: "#33261e", surface: "#fff5e6" },
    previewImage: "/assets/templates/vintage-love.png",
    accentImage: "/assets/brand/postmark.png",
    enabled: true,
    score: 91,
  },
  {
    id: "tpl_11",
    slug: "european-palace",
    name: "European Palace",
    arabicName: "قصر أوروبي",
    category: "فخم كلاسيكي",
    style: "palace",
    concept: "نوافذ قصر، ذهب معتق، وتفاصيل احتفالية واسعة.",
    opening: "Hall reveal",
    layout: "مدخل معماري كبير ثم أقسام بطول الصفحة.",
    typography: "عناوين رشيقة وBody متوازن.",
    palette: { primary: "#f0eadf", secondary: "#53615c", accent: "#b58b4f", ink: "#222827", surface: "#fbf7ef" },
    previewImage: "/assets/templates/european-palace.png",
    accentImage: "/assets/brand/chandelier.png",
    enabled: true,
    score: 92,
  },
  {
    id: "tpl_12",
    slug: "editorial-fashion",
    name: "Editorial Fashion",
    arabicName: "مجلة فاشون",
    category: "مجلة فاخرة",
    style: "editorial",
    concept: "غلاف مجلة عرس بأسماء ضخمة وصور كبيرة.",
    opening: "Magazine cover",
    layout: "Grid مجلة، أرقام كبيرة، وعناوين جانبية.",
    typography: "Editorial high contrast.",
    palette: { primary: "#f7f1ea", secondary: "#26231f", accent: "#bb3f46", ink: "#171411", surface: "#fffdf9" },
    previewImage: "/assets/templates/editorial-fashion.png",
    accentImage: "/assets/brand/magazine.png",
    enabled: true,
    score: 94,
  },
  {
    id: "tpl_13",
    slug: "desert-luxury",
    name: "Desert Luxury",
    arabicName: "فخامة الصحراء",
    category: "خليجي صحراوي",
    style: "desert",
    concept: "رمال ذهبية، ظل خيمة راقية، ودفء غروب.",
    opening: "Dune sweep",
    layout: "منحنيات رملية، بطاقة تفاصيل أفقية، وخريطة واضحة.",
    typography: "خط قوي متوازن.",
    palette: { primary: "#ead2ad", secondary: "#7f5941", accent: "#e2a74d", ink: "#33251b", surface: "#fff1de" },
    previewImage: "/assets/templates/desert-luxury.png",
    accentImage: "/assets/brand/dune.png",
    enabled: true,
    score: 91,
  },
  {
    id: "tpl_14",
    slug: "crystal-wedding",
    name: "Crystal Wedding",
    arabicName: "كريستال",
    category: "لامع راقي",
    style: "crystal",
    concept: "انعكاسات كريستال شفافة تفتح الدعوة بنور متكسر.",
    opening: "Prism glow",
    layout: "زجاج شفاف، حواف مضيئة، وحركة لمعان.",
    typography: "Sans رفيع ونظيف.",
    palette: { primary: "#eef7f8", secondary: "#91b9bd", accent: "#d2f1ee", ink: "#1e373b", surface: "#ffffff" },
    previewImage: "/assets/templates/crystal-wedding.png",
    accentImage: "/assets/brand/crystal.png",
    enabled: true,
    score: 90,
  },
  {
    id: "tpl_15",
    slug: "modern-minimal",
    name: "Modern Minimal",
    arabicName: "مينيمال حديث",
    category: "بسيط راقي",
    style: "minimal",
    concept: "مساحات هادئة، تفاصيل قليلة، وتركيز على الحدث.",
    opening: "Line draw",
    layout: "شبكة نظيفة، خطوط دقيقة، وأزرار واضحة.",
    typography: "Sans عربي واضح جدًا.",
    palette: { primary: "#f6f3ee", secondary: "#333a36", accent: "#87966d", ink: "#20231f", surface: "#ffffff" },
    previewImage: "/assets/templates/modern-minimal.png",
    accentImage: "/assets/brand/minimal-line.png",
    enabled: true,
    score: 93,
  },
  {
    id: "tpl_16",
    slug: "luxury-magazine",
    name: "Luxury Magazine",
    arabicName: "مجلة فاخرة",
    category: "تحريري فاخر",
    style: "editorial",
    concept: "دعوة كافتتاحية مجلة زفاف عالمية.",
    opening: "Page turn",
    layout: "أعمدة تحريرية، صور كبيرة، وملاحظات قصيرة.",
    typography: "خلط بين serif وsans.",
    palette: { primary: "#fbf6ed", secondary: "#5c1e2c", accent: "#d0a14a", ink: "#25171a", surface: "#fffaf4" },
    previewImage: "/assets/templates/luxury-magazine.png",
    accentImage: "/assets/brand/editorial-grid.png",
    enabled: true,
    score: 92,
  },
  {
    id: "tpl_17",
    slug: "garden-ceremony",
    name: "Garden Ceremony",
    arabicName: "مراسم الحديقة",
    category: "خارجي طبيعي",
    style: "garden",
    concept: "ممر حديقة، ضوء نهاري، وأوراق تتحرك مع الدخول.",
    opening: "Leaf path",
    layout: "ممر بصري يقود الضيف من الاسم للمكان.",
    typography: "خط ناعم مع أزرار واضحة.",
    palette: { primary: "#edf4e8", secondary: "#3f694f", accent: "#d6b15c", ink: "#1f3528", surface: "#fbfff7" },
    previewImage: "/assets/templates/garden-ceremony.png",
    accentImage: "/assets/brand/leaves.png",
    enabled: true,
    score: 94,
  },
  {
    id: "tpl_18",
    slug: "contemporary-elegant",
    name: "Contemporary Elegant",
    arabicName: "أناقة معاصرة",
    category: "راقي معاصر",
    style: "minimal",
    concept: "تركيب حديث بشريط جانبي وصور واسعة.",
    opening: "Panel slide",
    layout: "لوحة جانبية ثابتة ومحتوى متدرج.",
    typography: "وزن متوسط وتباين هادئ.",
    palette: { primary: "#f2f0ea", secondary: "#24464a", accent: "#bd8f5d", ink: "#1e2728", surface: "#ffffff" },
    previewImage: "/assets/templates/contemporary-elegant.png",
    accentImage: "/assets/brand/panel.png",
    enabled: true,
    score: 93,
  },
  {
    id: "tpl_19",
    slug: "romantic-classic",
    name: "Romantic Classic",
    arabicName: "رومانسي كلاسيكي",
    category: "كلاسيكي رومانسي",
    style: "classic",
    concept: "قلوب رقيقة، إطار كلاسيكي، وموسيقى هادئة.",
    opening: "Ribbon untie",
    layout: "بطاقة تقليدية مطورة مع أقسام قصيرة.",
    typography: "خط كلاسيكي بأسماء كبيرة.",
    palette: { primary: "#fff0ee", secondary: "#8f4450", accent: "#d9a4a7", ink: "#3f262b", surface: "#fffafa" },
    previewImage: "/assets/templates/romantic-classic.png",
    accentImage: "/assets/brand/ribbon.png",
    enabled: true,
    score: 91,
  },
  {
    id: "tpl_20",
    slug: "celestial-night",
    name: "Celestial Night",
    arabicName: "ليلة سماوية",
    category: "نجوم حالمة",
    style: "celestial",
    concept: "خريطة نجوم، مدار ذهبي، وافتتاحية كونية راقية.",
    opening: "Star map",
    layout: "دوائر مدارية، عداد سماوي، وتفاصيل مضيئة.",
    typography: "عناوين واسعة بتباين ليلي.",
    palette: { primary: "#121826", secondary: "#5a6c8f", accent: "#f0c878", ink: "#f7fbff", surface: "#182033" },
    previewImage: "/assets/templates/celestial-night.png",
    accentImage: "/assets/brand/starmap.png",
    enabled: true,
    score: 96,
  },
];

export function getTemplateBySlug(slug: string) {
  return invitationTemplates.find((template) => template.slug === slug);
}

export const featuredTemplates = invitationTemplates.filter((template) => template.score >= 94).slice(0, 8);
