ALTER TABLE "Invitation" ADD COLUMN IF NOT EXISTS "disabledAt" TIMESTAMP(3);
ALTER TABLE "Invitation" ADD COLUMN IF NOT EXISTS "disabledReason" TEXT;
ALTER TABLE "Invitation" ADD COLUMN IF NOT EXISTS "disabledBy" TEXT;
